const fs = require('fs');
const filePath = 'c:\\Users\\Mario\\Desktop\\EcomovingWeb\\src\\components\\CatalogHub.tsx';
const content = fs.readFileSync(filePath, 'utf8').split('\n');

// We want to replace everything from line 1471 (index 1470) to the end of the file.
// Line 1470 is currently '                                            </div>'
// We will replace from there until 1599 (the end).

const top = content.slice(0, 1470);

const middle = [
    '                                                </div>',
    '                                            </div>',
    '                                        ) : (',
    '                                            <div style={{ height: "100%", display: "flex", alignItems: "center", justifyContent: "center", opacity: 0.1 }}>',
    '                                                <Layers size={100} />',
    '                                            </div>',
    '                                        )}',
    '                                    </div>',
    '                                </React.Fragment>',
    '                            )}',
    '',
    '                             {activeTab === "gallery" && (',
    '                                <React.Fragment>',
    '                                    <div className="custom-scroll" style={{ borderRight: "1px solid rgba(255,255,255,0.05)", overflowY: "auto", padding: "32px 40px", backgroundColor: "rgba(0,0,0,0.2)" }}>',
    '                                        <h3 style={{ color: "var(--accent-gold)", fontSize: "11px", fontWeight: "900", letterSpacing: "3px", textTransform: "uppercase", marginBottom: "30px" }}>SECCIONES</h3>',
    '                                        <div style={{ display: "grid", gap: "10px" }}>',
    '                                            {["mugs", "botellas", "mochilas", "libretas", "ecologicos", "bolsas"].map(sec => (',
    '                                                <button',
    '                                                    key={sec}',
    '                                                    onClick={() => setSelectedGallerySection(sec)}',
    '                                                    style={{ textAlign: "left", padding: "15px 20px", background: selectedGallerySection === sec ? "rgba(0, 212, 189, 0.05)" : "transparent", border: "1px solid", borderColor: selectedGallerySection === sec ? "var(--accent-turquoise)" : "transparent", color: selectedGallerySection === sec ? "var(--accent-turquoise)" : "#555", borderRadius: "4px", textTransform: "uppercase", fontSize: "11px", fontWeight: "800", cursor: "pointer", letterSpacing: "2px" }}',
    '                                                >',
    '                                                    {sec}',
    '                                                </button>',
    '                                            ))}',
    '                                        </div>',
    '                                    </div>',
    '                                    <div className="custom-scroll" style={{ padding: "60px", overflowY: "auto", backgroundColor: "#050505" }}>',
    '                                        <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center", marginBottom: "60px" }}>',
    '                                            <h2 style={{ color: "white", fontFamily: "var(--font-heading)", fontSize: "32px", margin: 0, letterSpacing: "4px", textTransform: "uppercase" }}>',
    '                                                GALERÍA: <span style={{ color: "var(--accent-gold)" }}>{selectedGallerySection.toUpperCase()}</span>',
    '                                            </h2>',
    '                                            <div style={{ display: "flex", gap: "20px" }}>',
    '                                                <input',
    '                                                    type="file"',
    '                                                    multiple',
    '                                                    accept="image/*"',
    '                                                    id="gallery-upload"',
    '                                                    style={{ display: "none" }}',
    '                                                    onChange={handleGalleryUpload}',
    '                                                />',
    '                                                <label',
    '                                                    htmlFor="gallery-upload"',
    '                                                    style={{ background: "var(--accent-turquoise)", color: "black", padding: "15px 30px", borderRadius: "4px", fontSize: "12px", fontWeight: "900", cursor: uploadingGallery ? "not-allowed" : "pointer", letterSpacing: "2px", textTransform: "uppercase", display: "flex", alignItems: "center", gap: "10px" }}',
    '                                                >',
    '                                                    {uploadingGallery ? <RefreshCw className="animate-spin" size={18} /> : <Plus size={18} />}',
    '                                                    {uploadingGallery ? "SUBIENDO..." : "SUBIR IMÁGENES"}',
    '                                                </label>',
    '                                            </div>',
    '                                        </div>',
    '',
    '                                        <div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fill, minmax(250px, 1fr))", gap: "25px" }}>',
    '                                            {galleryImages.map((src, index) => (',
    '                                                <div key={index} style={{ position: "relative", aspectRatio: "4/3", borderRadius: "8px", overflow: "hidden", border: "1px solid rgba(255,255,255,0.05)", background: "#111" }}>',
    '                                                    <img src={src} alt="Galería" style={{ width: "100%", height: "100%", objectFit: "cover" }} />',
    '                                                    <button',
    '                                                        onClick={() => handleRemoveGalleryImage(index)}',
    '                                                        style={{ position: "absolute", top: "10px", right: "10px", background: "rgba(239, 68, 68, 0.9)", color: "white", border: "none", borderRadius: "50%", width: "30px", height: "30px", display: "flex", alignItems: "center", justifyContent: "center", cursor: "pointer", boxShadow: "0 4px 10px rgba(0,0,0,0.3)" }}',
    '                                                    >',
    '                                                        <X size={16} />',
    '                                                    </button>',
    '                                                </div>',
    '                                            ))}',
    '                                            {galleryImages.length === 0 && !uploadingGallery && (',
    '                                                <div style={{ gridColumn: "1 / -1", padding: "100px", textAlign: "center", border: "2px dashed rgba(255,255,255,0.05)", borderRadius: "12px", color: "#444" }}>',
    '                                                    <Plus size={60} style={{ marginBottom: "20px", opacity: 0.2 }} />',
    '                                                    <p style={{ letterSpacing: "2px", textTransform: "uppercase", fontSize: "12px" }}>No hay imágenes en esta galería</p>',
    '                                                </div>',
    '                                            )}',
    '                                        </div>',
    '                                    </div>',
    '                                </React.Fragment>',
    '                            )}',
    '',
    '                            {activeTab === "hero" && (',
    '                                <React.Fragment>',
    '                                    <div className="custom-scroll" style={{ padding: "60px", overflowY: "auto", backgroundColor: "#050505", gridColumn: "1 / -1" }}>',
    '                                        <div style={{ maxWidth: "1200px", margin: "0 auto" }}>',
    '                                            <h2 style={{ color: "white", fontFamily: "var(--font-heading)", fontSize: "32px", marginBottom: "40px", letterSpacing: "4px", textTransform: "uppercase" }}>',
    '                                                GESTIÓN DE <span style={{ color: "var(--accent-gold)" }}>BANNER PRINCIPAL (HERO)</span>',
    '                                            </h2>',
    '                                            <div style={{ display: "grid", gridTemplateColumns: "repeat(3, 1fr)", gap: "40px" }}>',
    '                                                {[1, 2, 3].map(slideNum => (',
    '                                                    <div key={slideNum} style={{ background: "rgba(255,255,255,0.02)", border: "1px solid rgba(255,255,255,0.05)", borderRadius: "8px", padding: "30px", display: "flex", flexDirection: "column", gap: "20px" }}>',
    '                                                        <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center" }}>',
    '                                                            <span style={{ fontSize: "14px", fontWeight: "900", color: "var(--accent-gold)", letterSpacing: "2px" }}>VISTA SLIDE {slideNum}</span>',
    '                                                            <button ',
    '                                                                onClick={() => handleSetAsHero(slideNum - 1)}',
    '                                                                style={{ padding: "8px 15px", background: "var(--accent-gold)", color: "black", border: "none", borderRadius: "2px", fontSize: "10px", fontWeight: "900", cursor: "pointer" }}',
    '                                                            >',
    '                                                                USAR SELECCIONADO',
    '                                                            </button>',
    '                                                        </div>',
    '                                                        <div style={{ aspectRatio: "16/9", background: "#000", borderRadius: "4px", border: "1px solid rgba(255,255,255,0.1)", overflow: "hidden", position: "relative" }}>',
    '                                                            <div style={{ position: "absolute", inset: 0, display: "flex", alignItems: "center", justifyContent: "center", opacity: 0.1 }}>',
    '                                                                <ImageIcon size={60} />',
    '                                                            </div>',
    '                                                            <p style={{ position: "absolute", bottom: "10px", left: "10px", margin: 0, fontSize: "10px", color: "#555", fontWeight: "800" }}>SLIDE_0{slideNum}.WEBP</p>',
    '                                                        </div>',
    '                                                        <div style={{ display: "flex", flexDirection: "column", gap: "10px" }}>',
    '                                                            <button style={{ padding: "15px", background: "rgba(0, 212, 189, 0.05)", border: "1px solid var(--accent-turquoise)", color: "var(--accent-turquoise)", borderRadius: "4px", fontSize: "11px", fontWeight: "800", cursor: "pointer", textTransform: "uppercase" }}>SUBIR NUEVA IMAGEN</button>',
    '                                                        </div>',
    '                                                    </div>',
    '                                                ))}',
    '                                            </div>',
    '                                        </div>',
    '                                    </div>',
    '                                </React.Fragment>',
    '                            )}',
    '',
    '                            {activeTab === "marketing" && (',
    '                                <React.Fragment>',
    '                                    <div className="custom-scroll" style={{ padding: "60px", overflowY: "auto", backgroundColor: "#050505", gridColumn: "1 / -1" }}>',
    '                                        <div style={{ maxWidth: "1200px", margin: "0 auto" }}>',
    '                                            <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center", marginBottom: "40px" }}>',
    '                                                <h2 style={{ color: "white", fontFamily: "var(--font-heading)", fontSize: "32px", margin: 0, letterSpacing: "4px", textTransform: "uppercase" }}>',
    '                                                    AI CONTENT <span style={{ color: "var(--accent-gold)" }}>FACTORY</span>',
    '                                                </h2>',
    '                                                <div style={{ display: "flex", gap: "15px" }}>',
    '                                                    <button',
    '                                                        onClick={handleGenerateMarketingAI}',
    '                                                        disabled={isGeneratingAI || !selectedProduct}',
    '                                                        style={{ background: "var(--accent-turquoise)", color: "black", padding: "15px 30px", borderRadius: "4px", fontSize: "12px", fontWeight: "900", cursor: "pointer", textTransform: "uppercase" }}',
    '                                                    >',
    '                                                        {isGeneratingAI ? "GENERANDO..." : "GENERAR MARKETING (GEMINI)"}',
    '                                                    </button>',
    '                                                    <button',
    '                                                        onClick={handleSaveMarketingAI}',
    '                                                        disabled={!generatedMarketing || isSaving}',
    '                                                        style={{ background: "var(--accent-gold)", color: "black", padding: "15px 30px", borderRadius: "4px", fontSize: "12px", fontWeight: "900", cursor: "pointer", textTransform: "uppercase" }}',
    '                                                    >',
    '                                                        {isSaving ? "GUARDANDO..." : "GUARDAR Y ENVIAR"}',
    '                                                    </button>',
    '                                                </div>',
    '                                            </div>',
    '',
    '                                            {generatedMarketing ? (',
    '                                                <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: "40px" }}>',
    '                                                    <div style={{ background: "rgba(255,255,255,0.02)", border: "1px solid rgba(255,255,255,0.05)", padding: "30px", borderRadius: "8px" }}>',
    '                                                        <h3 style={{ color: "var(--accent-gold)", fontSize: "14px", marginBottom: "20px" }}>ESTRUCTURA DE DATOS</h3>',
    '                                                        <div style={{ display: "flex", flexDirection: "column", gap: "20px" }}>',
    '                                                            <div>',
    '                                                                <label style={{ color: "#555", fontSize: "10px", display: "block", marginBottom: "5px" }}>ASUNTO</label>',
    '                                                                <input readOnly value={generatedMarketing.subject} style={{ width: "100%", background: "#000", border: "1px solid #333", padding: "12px", color: "white" }} />',
    '                                                            </div>',
    '                                                            <div>',
    '                                                                <label style={{ color: "#555", fontSize: "10px", display: "block", marginBottom: "5px" }}>TITULAR L1</label>',
    '                                                                <input readOnly value={generatedMarketing.part1} style={{ width: "100%", background: "#000", border: "1px solid #333", padding: "12px", color: "white" }} />',
    '                                                            </div>',
    '                                                            <div>',
    '                                                                <label style={{ color: "#555", fontSize: "10px", display: "block", marginBottom: "5px" }}>DESCRIPCIÓN L2</label>',
    '                                                                <textarea readOnly value={generatedMarketing.part2} style={{ width: "100%", height: "100px", background: "#000", border: "1px solid #333", padding: "12px", color: "#888" }} />',
    '                                                            </div>',
    '                                                        </div>',
    '                                                    </div>',
    '                                                    <div style={{ background: "#fff", padding: "40px", borderRadius: "8px", overflowY: "auto", maxHeight: "600px" }}>',
    '                                                        <div dangerouslySetInnerHTML={{ __html: generatedMarketing.html.replace("IMAGE_URL_PLACEHOLDER", activeImage || "") }} />',
    '                                                    </div>',
    '                                                </div>',
    '                                            ) : (',
    '                                                <div style={{ height: "400px", display: "flex", flexDirection: "column", alignItems: "center", justifyContent: "center", opacity: 0.2, border: "2px dashed #222" }}>',
    '                                                    <Sparkles size={60} />',
    '                                                    <p style={{ marginTop: "20px", letterSpacing: "2px" }}>SELECCIONA UN PRODUCTO Y PULSA "GENERAR"</p>',
    '                                                </div>',
    '                                            )}',
    '                                        </div>',
    '                                    </div>',
    '                                </React.Fragment>',
    '                            )}',
    '                        </div>',
    '                    </motion.div>',
    '                </motion.div>',
    '            )}',
    '        </AnimatePresence>',
    '    );',
    '}',
    ''
];

const newContent = [...top, ...middle].join('\n');
fs.writeFileSync(filePath, newContent, 'utf8');
console.log('Successfully applied FINAL recovery to CatalogHub.tsx');
