const fs = require('fs');
const filePath = 'c:\\Users\\Mario\\Desktop\\EcomovingWeb\\src\\components\\CatalogHub.tsx';
const content = fs.readFileSync(filePath, 'utf8').split('\n');

// We want to replace the block from "Right Column" (where SKU and Category end)
// until "Gallery content" ends.

// Current line 1419 is index 1418 (the end of Category row)
// Current line 1460 is index 1459

const top = content.slice(0, 1419);
const bottom = content.slice(1518); // Skip the mangled gallery/catalog transition

const middle = [
    '                                                        </div>',
    '',
    '                                                        {/* Título y Specs (Added) */}',
    '                                                        <div style={{ marginTop: "20px" }}>',
    '                                                            <label style={{ display: "block", fontSize: "11px", color: "var(--accent-gold)", marginBottom: "10px", fontWeight: "800", letterSpacing: "3px", textTransform: "uppercase" }}>NOMBRE DEL PRODUCTO</label>',
    '                                                            <input',
    '                                                                value={selectedProduct.name}',
    '                                                                onChange={(e) => handleUpdateProduct({ name: e.target.value })}',
    '                                                                style={{ width: "100%", backgroundColor: "rgba(255,255,255,0.02)", border: "1px solid rgba(255,255,255,0.05)", borderRadius: "2px", padding: "15px", color: "white", fontSize: "18px", fontWeight: "600", outline: "none" }}',
    '                                                            />',
    '                                                        </div>',
    '',
    '                                                        <div style={{ flex: 1, display: "flex", flexDirection: "column", marginTop: "20px" }}>',
    '                                                            <label style={{ display: "block", fontSize: "11px", color: "var(--accent-gold)", marginBottom: "10px", fontWeight: "800", letterSpacing: "2px", textTransform: "uppercase" }}>CARACTERÍSTICAS</label>',
    '                                                            <textarea',
    '                                                                value={selectedProduct.technical_specs?.join("\\n") || ""}',
    '                                                                onChange={(e) => handleUpdateProduct({ technical_specs: e.target.value.split("\\n").filter(l => l.trim()) })}',
    '                                                                style={{ width: "100%", flex: 1, minHeight: "300px", backgroundColor: "rgba(255,255,255,0.01)", border: "1px solid rgba(255,255,255,0.05)", borderRadius: "2px", padding: "20px", color: "#ccc", fontSize: "14px", outline: "none", resize: "none", lineHeight: "1.6" }}',
    '                                                            />',
    '                                                        </div>',
    '',
    '                                                        {/* Botones de Acción (Added) */}',
    '                                                        <div style={{ marginTop: "30px", display: "flex", gap: "15px", paddingBottom: "30px" }}>',
    '                                                            <button',
    '                                                                onClick={handleSaveChanges}',
    '                                                                disabled={isSaving}',
    '                                                                style={{ flex: 1, backgroundColor: isSaving ? "#333" : "var(--accent-gold)", color: "black", border: "none", padding: "20px", fontSize: "14px", fontWeight: "900", letterSpacing: "2px", cursor: isSaving ? "not-allowed" : "pointer", borderRadius: "4px", textTransform: "uppercase", display: "flex", alignItems: "center", justifyContent: "center", gap: "10px" }}',
    '                                                            >',
    '                                                                {isSaving ? <Loader2 className="animate-spin" size={20} /> : <Save size={20} />}',
    '                                                                GUARDAR',
    '                                                            </button>',
    '                                                            <button',
    '                                                                onClick={handlePublish}',
    '                                                                style={{ flex: 1, backgroundColor: "var(--accent-turquoise)", color: "black", border: "none", padding: "20px", fontSize: "14px", fontWeight: "900", letterSpacing: "2px", cursor: "pointer", borderRadius: "4px", textTransform: "uppercase", display: "flex", alignItems: "center", justifyContent: "center", gap: "10px" }}',
    '                                                            >',
    '                                                                <Globe size={20} />',
    '                                                                PUBLICAR',
    '                                                            </button>',
    '                                                            <button',
    '                                                                onClick={handleReject}',
    '                                                                style={{ backgroundColor: "rgba(239, 68, 68, 0.1)", color: "#ef4444", border: "1px solid #ef4444", padding: "20px", borderRadius: "4px", cursor: "pointer" }}',
    '                                                            >',
    '                                                                <Trash2 size={20} />',
    '                                                            </button>',
    '                                                        </div>',
    '                                                    </div>',
    '                                                </div>',
    '                                            </div>',
    '                                        ) : (',
    '                                            <div style={{ height: "100%", display: "flex", alignItems: "center", justifyContent: "center", opacity: 0.1 }}>',
    '                                                <Layers size={100} />',
    '                                            </div>',
    '                                        )}',
    '                                    </React.Fragment>',
    '                                )}',
    '',
    '                            {activeTab === "gallery" && (',
    '                                <React.Fragment>',
    '                                    <div className="custom-scroll" style={{ borderRight: "1px solid rgba(255,255,255,0.05)", overflowY: "auto", padding: "32px 40px", backgroundColor: "rgba(0,0,0,0.2)" }}>',
    '                                        <h3 style={{ color: "var(--accent-gold)", fontSize: "11px", fontWeight: "900", letterSpacing: "3px", textTransform: "uppercase", marginBottom: "30px" }}>SECCIONES</h3>',
    '                                        <div style={{ display: "grid", gap: "10px" }}>',
    '                                            {["mugs", "botellas", "mochilas", "libretas", "ecologicos", "bolsas"].map(sec => (',
    '                                                <button',
    '                                                    key={sec}',
    '                                                    onClick={() => setSelectedGallerySection(sec)}',
    '                                                    style={{ textAlign: "left", padding: "15px 20px", background: selectedGallerySection === sec ? "rgba(0, 212, 189, 0.05)" : "transparent", border: "1px solid", borderColor: selectedGallerySection === sec ? "var(--accent-turquoise)" : "transparent", color: selectedGallerySection === sec ? "var(--accent-turquoise)" : "#555", borderRadius: "4px", textTransform: "uppercase", fontSize: "11px", fontWeight: "800", cursor: "pointer", letterSpacing: "2px" }}',
    '                                                >',
    '                                                    {sec}',
    '                                                </button>',
    '                                            ))}',
    '                                        </div>',
    '                                    </div>',
    '                                    <div className="custom-scroll" style={{ padding: "60px", overflowY: "auto", backgroundColor: "#050505" }}>',
    '                                        <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center", marginBottom: "60px" }}>',
    '                                            <h2 style={{ color: "white", fontFamily: "var(--font-heading)", fontSize: "32px", margin: 0, letterSpacing: "4px", textTransform: "uppercase" }}>',
    '                                                GALERÍA: <span style={{ color: "var(--accent-gold)" }}>{selectedGallerySection.toUpperCase()}</span>',
    '                                            </h2>',
    '                                            <div style={{ display: "flex", gap: "20px" }}>',
    '                                                <input',
    '                                                    type="file"',
    '                                                    multiple',
    '                                                    accept="image/*"',
    '                                                    id="gallery-upload"',
    '                                                    style={{ display: "none" }}',
    '                                                    onChange={handleGalleryUpload}',
    '                                                />',
    '                                                <label',
    '                                                    htmlFor="gallery-upload"',
    '                                                    style={{',
    '                                                        background: "var(--accent-turquoise)",',
    '                                                        color: "black",',
    '                                                        padding: "15px 30px",',
    '                                                        borderRadius: "4px",',
    '                                                        fontSize: "12px",',
    '                                                        fontWeight: "900",',
    '                                                        cursor: uploadingGallery ? "not-allowed" : "pointer",',
    '                                                        letterSpacing: "2px",',
    '                                                        textTransform: "uppercase",',
    '                                                        display: "flex",',
    '                                                        alignItems: "center",',
    '                                                        gap: "10px"',
    '                                                    }}',
    '                                                >',
    '                                                    {uploadingGallery ? <RefreshCw className="animate-spin" size={18} /> : <Plus size={18} />}',
    '                                                    {uploadingGallery ? "SUBIENDO..." : "SUBIR IMÁGENES"}',
    '                                                </label>',
    '                                            </div>'
];

const newContent = [...top, ...middle, ...bottom].join('\n');
fs.writeFileSync(filePath, newContent, 'utf8');
console.log('Successfully applied v2 fix to CatalogHub.tsx');
